# Class 6: Text Basics - Tutorial

https://spacy.io/models/da

In [1]:
import numpy as np

import spacy
from spacy.lang.da.examples import sentences 

In [4]:
#!python -m spacy download da_core_news_sm
#!python -m spacy download en_core_web_sm

## Spacy Models

In [5]:
spacy_pipeline = spacy.load("da_core_news_sm")

In [6]:
type(spacy_pipeline)

spacy.lang.da.Danish

## Tokenization

We pass whatever text we want to process to `spacy_pipeline`, which returns a `Doc` container object (https://spacy.io/api/doc) containing the tokenized text and a number of annotations for each token. 


In [7]:
# Generate sample text
sample_text = sentences[0]

In [9]:
# Instantiate SpaCy pipeline
doc = spacy_pipeline(sample_text)

In [10]:
# Print doc
print(doc)

Apple overvejer at købe et britisk startup for 1 milliard dollar.


In [11]:
# # Looks like a standard string, but it's not - Check type
type(doc)

spacy.tokens.doc.Doc

In [12]:
# We can iterate over the Doc object to access the tokens - note that we access the token by the .text attribute
tokens0 = [t.text for t in doc]

In [14]:
# Alternative tokenizer: .split()
tokens1 = sample_text.split(' ')

In [15]:
len(tokens0), len(tokens1)

(12, 11)

In [16]:
tokens1

['Apple',
 'overvejer',
 'at',
 'købe',
 'et',
 'britisk',
 'startup',
 'for',
 '1',
 'milliard',
 'dollar.']

In [17]:
tokens0

['Apple',
 'overvejer',
 'at',
 'købe',
 'et',
 'britisk',
 'startup',
 'for',
 '1',
 'milliard',
 'dollar',
 '.']

In [18]:
# We can view an individual token by indexing into the Doc object
print(doc[0])

Apple


In [19]:
# Also looks like a string, but it's not -- Check type
print(type(doc[0]))

<class 'spacy.tokens.token.Token'>


In [20]:
# Slicing a Doc object returns a Span object.
print(doc[0:3])
print(type(doc[0:3]))

Apple overvejer at
<class 'spacy.tokens.span.Span'>


In [21]:
# Access a token's index in a sentence
print([(t.text, t.i) for t in doc])

[('Apple', 0), ('overvejer', 1), ('at', 2), ('købe', 3), ('et', 4), ('britisk', 5), ('startup', 6), ('for', 7), ('1', 8), ('milliard', 9), ('dollar', 10), ('.', 11)]


In [22]:
# Spacy's tokenization is _non-destructive_, which means the original input can be reconstructed from the tokens.
# You can view the original input like so:
print(doc.text)

Apple overvejer at købe et britisk startup for 1 milliard dollar.


In [23]:
# And by reconstructing, we also now have a string object
print(type(doc.text))

<class 'str'>


In [24]:
# It is even non-destructive from each individual token as well
print(doc[0].doc.text)

Apple overvejer at købe et britisk startup for 1 milliard dollar.


In [25]:
print(type(doc[0].doc.text))

<class 'str'>


In [26]:
# It also possible to tokenize multiple sentences at once - but spacy requires a string input
s = sentences[0] + ' ' + sentences[1]
# s = [sentences[0]] + [sentences[1]]

In [28]:
doc = spacy_pipeline(s)

In [30]:
# Look at individual sentences (there should be two 'Span' objects).
print([sent for sent in doc.sents])

[Apple overvejer at købe et britisk startup for 1 milliard dollar., Selvkørende biler flytter forsikringsansvaret over på producenterne.]


In [31]:
# We can also access individual tokens, but where the sentence structure is hidden
print([t.text for t in doc])

['Apple', 'overvejer', 'at', 'købe', 'et', 'britisk', 'startup', 'for', '1', 'milliard', 'dollar', '.', 'Selvkørende', 'biler', 'flytter', 'forsikringsansvaret', 'over', 'på', 'producenterne', '.']


In [34]:
# Use a nested list comprehension to maintain the sentence structure while looking at individual tokens
[[t.text for t in sent] for sent in doc.sents]

[['Apple',
  'overvejer',
  'at',
  'købe',
  'et',
  'britisk',
  'startup',
  'for',
  '1',
  'milliard',
  'dollar',
  '.'],
 ['Selvkørende',
  'biler',
  'flytter',
  'forsikringsansvaret',
  'over',
  'på',
  'producenterne',
  '.']]

In [ ]:
# Why choose a pretrained pipeline over the .split() method?

s = 'Toronto ligger 159km fra Buffalo.'

doc = spacy_pipeline(s)

# Consider the spacy result:
tokens0 = [t.text for t in doc]
print(tokens0)

In [ ]:
# And the .split() result
tokens1 = s.split()
print(tokens1)

In [ ]:
# So far we have tokenized sentences or at most two sentences. Imagine we have a corpus. 
# tokens = [spacy_pipeline(x) for x in sentences]

## Preprocessing

* Stopwords/digits
* Casing
* Word reduction (stemming and lemmatization)

In [37]:
# Define a list with Danish stopwords
stop_words = sorted(spacy_pipeline.Defaults.stop_words)

In [40]:
# Print stopwords
print(stop_words)

['af', 'aldrig', 'alene', 'alle', 'allerede', 'alligevel', 'alt', 'altid', 'anden', 'andet', 'andre', 'at', 'bag', 'begge', 'blandt', 'blev', 'blive', 'bliver', 'burde', 'bør', 'da', 'de', 'dem', 'den', 'denne', 'dens', 'der', 'derefter', 'deres', 'derfor', 'derfra', 'deri', 'dermed', 'derpå', 'derved', 'det', 'dette', 'dig', 'din', 'dine', 'disse', 'dog', 'du', 'efter', 'egen', 'eller', 'ellers', 'en', 'end', 'endnu', 'ene', 'eneste', 'enhver', 'ens', 'enten', 'er', 'et', 'flere', 'flest', 'fleste', 'for', 'foran', 'fordi', 'forrige', 'fra', 'få', 'før', 'først', 'gennem', 'gjorde', 'gjort', 'god', 'gør', 'gøre', 'gørende', 'ham', 'han', 'hans', 'har', 'havde', 'have', 'hel', 'heller', 'hen', 'hende', 'hendes', 'henover', 'her', 'herefter', 'heri', 'hermed', 'herpå', 'hun', 'hvad', 'hvem', 'hver', 'hvilke', 'hvilken', 'hvilkes', 'hvis', 'hvor', 'hvordan', 'hvorefter', 'hvorfor', 'hvorfra', 'hvorhen', 'hvori', 'hvorimod', 'hvornår', 'hvorved', 'i', 'igen', 'igennem', 'ikke', 'imellem',

In [41]:
# Compute length of stopwords
len(stop_words)

219

In [42]:
print(tokens0)

['Apple', 'overvejer', 'at', 'købe', 'et', 'britisk', 'startup', 'for', '1', 'milliard', 'dollar', '.']


In [43]:
# Removal of stopwords using list comprehension
[x for x in tokens0 if x not in stop_words]

['Apple',
 'overvejer',
 'købe',
 'britisk',
 'startup',
 '1',
 'milliard',
 'dollar',
 '.']

In [49]:
# Removal of digits
[x for x in tokens0 if not x.isdigit() and x not in ['.', ',']]

['Apple',
 'overvejer',
 'at',
 'købe',
 'et',
 'britisk',
 'startup',
 'for',
 'milliard',
 'dollar']

### Casing

In [50]:
s

'Apple overvejer at købe et britisk startup for 1 milliard dollar. Selvkørende biler flytter forsikringsansvaret over på producenterne.'

In [51]:
# Case-folding using the builtin .lower() function
s.lower().split()

['apple',
 'overvejer',
 'at',
 'købe',
 'et',
 'britisk',
 'startup',
 'for',
 '1',
 'milliard',
 'dollar.',
 'selvkørende',
 'biler',
 'flytter',
 'forsikringsansvaret',
 'over',
 'på',
 'producenterne.']

In [52]:
# Case-folding using the .lower_ attribute
print([t.lower_ for t in doc])

['apple', 'overvejer', 'at', 'købe', 'et', 'britisk', 'startup', 'for', '1', 'milliard', 'dollar', '.', 'selvkørende', 'biler', 'flytter', 'forsikringsansvaret', 'over', 'på', 'producenterne', '.']


In [53]:
# Conditional lowering
print([t.lower_ if not t.is_sent_start else t for t in doc])

[Apple, 'overvejer', 'at', 'købe', 'et', 'britisk', 'startup', 'for', '1', 'milliard', 'dollar', '.', Selvkørende, 'biler', 'flytter', 'forsikringsansvaret', 'over', 'på', 'producenterne', '.']


In [54]:
# SpaCy performs advanced preprocessing steps under the hood such as NER, POS, and Parsing
s = 'Toronto ligger 159km fra Buffalo.'
[(t.text, t.ent_type_) for t in spacy_pipeline(s)]

[('Toronto', ''),
 ('ligger', ''),
 ('159', ''),
 ('km', ''),
 ('fra', ''),
 ('Buffalo', 'PER'),
 ('.', '')]

In [55]:
# The results are not always as we want. Try replace 'Toronto' with 'København'
s = 'København ligger 159km fra Buffalo.'
[(t.text, t.ent_type_) for t in spacy_pipeline(s)]

[('København', 'LOC'),
 ('ligger', ''),
 ('159', ''),
 ('km', ''),
 ('fra', ''),
 ('Buffalo', 'PER'),
 ('.', '')]

In [56]:
# Load english pipeline
spacy_pipeline_en = spacy.load('en_core_web_sm')

In [57]:
s = 'Toronto ligger 159km fra Buffalo.'
[(t.text, t.ent_type_) for t in spacy_pipeline_en(s)]

[('Toronto', 'GPE'),
 ('ligger', ''),
 ('159', 'QUANTITY'),
 ('km', 'QUANTITY'),
 ('fra', ''),
 ('Buffalo', 'GPE'),
 ('.', '')]

In [58]:
# We can get SpaCy to explain its abbreviations
spacy.explain('GPE')

'Countries, cities, states'

In [59]:
# Conditional lowering using NER as exceptions
print([t.lower_ if t.ent_type_ not in ['GPE', 'LOC'] else t for t in spacy_pipeline_en(s)])

[Toronto, 'ligger', '159', 'km', 'fra', Buffalo, '.']


### Word Reduction

In [60]:
from nltk.stem.snowball import DanishStemmer
stemmer = DanishStemmer()

In [61]:
# s = 'Udlændinge kommer herop og begår kriminalitet'
s = 'Toronto ligger 159km fra Buffalo.'

In [62]:
# Stemming using NLTK
[stemmer.stem(t.text) for t in spacy_pipeline(s)]

['toronto', 'lig', '159', 'km', 'fra', 'buffalo', '.']

In [63]:
# Lemmatization using SpaCy
[t.lemma_ for t in spacy_pipeline(s)]

['Toronto', 'ligge', '159', 'kilometer', 'fra', 'Buffalo', '.']

## Vectorization

* Binary and count
* TF-IDF

### Binary and Count Vectorization

In [64]:
# Generate a corpus of sentences.
corpus = [
    "Red Bull drops hint on F1 engine.",
    "Honda exits F1, leaving F1 partner Red Bull.",
    "Hamilton eyes record eighth F1 title.",
    "Aston Martin announces sponsor."]

In [65]:
# Import classes and functions from sklearn
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [66]:
# Initiate a BoW vectorizer
vectorizer = CountVectorizer(binary=True)

In [69]:
vectorizer.vocabulary_

{'red': 17,
 'bull': 2,
 'drops': 3,
 'hint': 10,
 'on': 14,
 'f1': 8,
 'engine': 5,
 'honda': 11,
 'exits': 6,
 'leaving': 12,
 'partner': 15,
 'hamilton': 9,
 'eyes': 7,
 'record': 16,
 'eighth': 4,
 'title': 19,
 'aston': 1,
 'martin': 13,
 'announces': 0,
 'sponsor': 18}

In [68]:
# Build vocabulary
vectorizer.fit(corpus)

CountVectorizer(binary=True)

In [70]:
# See vocab
print(vectorizer.get_feature_names_out())
vectorizer.vocabulary_

['announces' 'aston' 'bull' 'drops' 'eighth' 'engine' 'exits' 'eyes' 'f1'
 'hamilton' 'hint' 'honda' 'leaving' 'martin' 'on' 'partner' 'record'
 'red' 'sponsor' 'title']


{'red': 17,
 'bull': 2,
 'drops': 3,
 'hint': 10,
 'on': 14,
 'f1': 8,
 'engine': 5,
 'honda': 11,
 'exits': 6,
 'leaving': 12,
 'partner': 15,
 'hamilton': 9,
 'eyes': 7,
 'record': 16,
 'eighth': 4,
 'title': 19,
 'aston': 1,
 'martin': 13,
 'announces': 0,
 'sponsor': 18}

In [71]:
# Sort vocab
dict(sorted(vectorizer.vocabulary_.items(), key=lambda x: x[1]))

{'announces': 0,
 'aston': 1,
 'bull': 2,
 'drops': 3,
 'eighth': 4,
 'engine': 5,
 'exits': 6,
 'eyes': 7,
 'f1': 8,
 'hamilton': 9,
 'hint': 10,
 'honda': 11,
 'leaving': 12,
 'martin': 13,
 'on': 14,
 'partner': 15,
 'record': 16,
 'red': 17,
 'sponsor': 18,
 'title': 19}

In [72]:
# Apply the vocab to the corpus
bow = vectorizer.transform(corpus)

In [74]:
# Convert sparse matrix to np array
bow_array = bow.toarray()
print(bow_array)

[[0 0 1 1 0 1 0 0 1 0 1 0 0 0 1 0 0 1 0 0]
 [0 0 1 0 0 0 1 0 1 0 0 1 1 0 0 1 0 1 0 0]
 [0 0 0 0 1 0 0 1 1 1 0 0 0 0 0 0 1 0 0 1]
 [1 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0]]


In [76]:
# Define custom tokenizer (more steps can easily be added)
def spacy_tokenizer(doc):
    toks = [t for t in spacy_pipeline_en(doc) if not t.is_punct]
    return [t.text for t in toks]

In [77]:
# Instantiate CountVectorizer and apply fit_transform
vectorizer = CountVectorizer(tokenizer=spacy_tokenizer, lowercase=False, binary=False, decode_error='ignore', token_pattern=None)
bow = vectorizer.fit_transform(corpus)

In [78]:
bow_array = bow.toarray()

In [80]:
# Compute pairwise cosine similarity
cosine_similarity(bow_array)

array([[1.        , 0.47809144, 0.15430335, 0.        ],
       [0.47809144, 1.        , 0.25819889, 0.        ],
       [0.15430335, 0.25819889, 1.        , 0.        ],
       [0.        , 0.        , 0.        , 1.        ]])

In [ ]:
# Manual computation of cosine similarity
np.dot(bow_array[0], bow_array[1]) / (np.linalg.norm(bow_array[0]) * np.linalg.norm(bow_array[1]))

### TF-IDF

In [ ]:
from sklearn.datasets import fetch_20newsgroups
from sklearn.feature_extraction.text import TfidfVectorizer

We'll use the **20 newsgroups** dataset, which is a collection of 18,000 newsgroup posts across 20 topics.<br>
https://scikit-learn.org/stable/datasets/real_world.html#the-20-newsgroups-text-dataset
<br><br>
List of datasets available:<br>
https://scikit-learn.org/stable/datasets.html#datasets

The **datasets** module includes fetchers for each dataset in scikit-learn. For our purposes, we'll fetch only the posts from the *sci.space* topic, and skip on headers, footers, and quoting of other posts.<br>
https://scikit-learn.org/stable/modules/generated/sklearn.datasets.fetch_20newsgroups.html#sklearn.datasets.fetch_20newsgroups
<br><br>
By default, the fetcher retrieves the *training* subset of the data only. If you don't know what that means, it'll become clear later in the course when we discuss modelling. For now, it doesn't matter for our purposes.

In [ ]:
corpus = fetch_20newsgroups(categories=['sci.space'],
                            remove=('headers', 'footers', 'quotes'))

In [ ]:
# We don't need named-entity recognition nor dependency parsing for
# this so these components are disabled. This will speed up the
# pipeline. We do need part-of-speech tagging however.
unwanted_pipes = ["ner", "parser"]

# For this exercise, we'll remove punctuation and spaces (which
# includes newlines), filter for tokens consisting of alphabetic
# characters, and return the lemma (which require POS tagging).
def spacy_tokenizer(doc):
    with nlp.disable_pipes(*unwanted_pipes):
        return [t.lemma_ for t in nlp(doc) if \
                not t.is_punct and \
                not t.is_space and \
                t.is_alpha]

In [ ]:
%%time
# Use the default settings of TfidfVectorizer.
vectorizer = TfidfVectorizer(tokenizer=spacy_tokenizer, token_pattern=None)
features = vectorizer.fit_transform(corpus.data)

In [ ]:
# The number of unique tokens.
print(len(vectorizer.get_feature_names_out()))

In [ ]:
# The dimensions of our feature matrix. X rows (documents) by Y columns (tokens).
print(features.shape)

In [ ]:
# View first two posts.
corpus.data[:2]

In [ ]:
#
vectorizer.vocabulary_['satellite']

In [ ]:
# What the encoding of the first document looks like in sparse format.
print(features[0])

In [ ]:
# Transform the query into a TF-IDF vector.
query = ["lunar orbit"]
query_tfidf = vectorizer.transform(query)

In [ ]:
# Calculate the cosine similarities between the query and each document.
# We're calling flatten() here becaue cosine_similarity returns a list
# of lists and we just want a single list.
cosine_similarities = cosine_similarity(features, query_tfidf).flatten()

In [ ]:
def top_k(arr, k):
    kth_largest = (k + 1) * -1
    return np.argsort(arr)[:kth_largest:-1]

In [ ]:
# So for our query above, these are the top five documents.
top_related_indices = top_k(cosine_similarities, 5)
print(top_related_indices)

In [ ]:
# Let's take a look at their respective cosine similarities.
print(cosine_similarities[top_related_indices])

In [ ]:
# Top match.
print(corpus.data[top_related_indices[0]])

In [ ]:
# Second-best match.
print(corpus.data[top_related_indices[1]])

In [ ]:
# Try a different query
query = ["satellite"]
query_tfidf = vectorizer.transform(query)

cosine_similarities = cosine_similarity(features, query_tfidf).flatten()
top_related_indices = top_k(cosine_similarities, 5)

print(top_related_indices)
print(cosine_similarities[top_related_indices])

In [ ]:
print(corpus.data[top_related_indices[0]])